### ISSUE TITLE
typesetting matrices

### ISSUE THREAD

**Issue by trevorcampbell** [trevorcampbell/shortex#18]
Right now we typeset matrices via
```
\bmat
...
\ema 
```
which is a shortcut for `\begin{pmatrix}...\end{pmatrix}`. I want to use square brackets around my matrices -- I think it's more standard/common anyway (`\begin{bmatrix}...\end{bmatrix}`). Can we do

```
\bmat
\emat
```
for square brackets (or maybe `\bbmat...\ebmat`), and

```
\bpmat
\epmat
```
for parentheses?

**Comment by jhuggins** [comment]
Yeah I think the consistent notation you suggest is good. Matches how we name bracket types

**Comment by trevorcampbell** [comment]
Just to confirm -- do you like `\bbmat & \bpmat` or `\bmat & \bpmat` ?

**Comment by jhuggins** [comment]
Yes!

**Comment by trevorcampbell** [comment]
I'll assume you mean the first one and make a PR :) see #19
