### ISSUE TITLE
commenter names/colors

### ISSUE THREAD

**Issue by trevorcampbell** [trevorcampbell/shortex#35]
Right now we have `\PRB`, `\RMK`, `\mPRB`, `\mRMK` for problem/remark in-text/margin, and `\HLT` for highlighting text. I'm working on a paper right now with multiple people doing editing, and I find it super helpful to have comments denoted by initials.

I wonder if we can do something like

```
\usepackage[commenters=TC,JH,JN]{shortex}
```

and then have commenting commands (perhaps with commenter-specific colors!) like
```
\cTC   (comment TC)
\mcTC  (margin comment TC)
\pTC  (problem TC)
\mpTC  (margin problem TC)
\hTC   (highlight TC)
```

and furthermore, I wonder if the "problem" type comments are kind of pointless. When editing I don't feel the need to distinguish between "comment" and "problem" -- I just use comment for everything. Perhaps instead of "problem" we have bold comment like `\bcTC` if you want something to stick out more.

**Comment by jhuggins** [comment]
I like the idea of the individual comment commands! 

I use the problem comment for major issues / high-priority items, often when I'm still writing, that I want to make sure I see – e.g., part of a proof that's missing  or incorrect, or to highlight something that needs to be written. In practice these are always inline. I use the remark comment for all the more mundane stuff.

**Comment by jhuggins** [comment]
I love it! Much more streamlined and intuitive

**Comment by trevorcampbell** [comment]
One more thing while I fix this: we need these comments to work in figure captions. Right now I get

```
rsion <1.7>, but at most version <1.5> allowed
! Missing \endcsname inserted.
<to be read again> 
                   \csname\endcsname 
l.133     and blah blah \fTBD{adsf}}
```

**Comment by trevorcampbell** [comment]
And in algorithm block:
```
! LaTeX Error: Float(s) lost.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.70 \clearpage
```

**Comment by jhuggins** [comment]
The `\marginpar` command can't be used in floats. If we want it to work with floats, looks like we need to switch to the `\marginnote` package: https://www.ctan.org/pkg/marginnote

**Comment by jhuggins** [comment]
One related change I would propose is that highlight should note include any additional symbols – just change the text color.
