### ISSUE TITLE
package option / default for creating the "usual" set of character style macros

### ISSUE THREAD

**Issue by trevorcampbell** [trevorcampbell/shortex#38]
My instinct is to have the default be "all the usual stuff" so that people aren't surprised when things don't work (I just had a user have this happen and ask me what was going on), and then have a `lightweight` option or something like that to avoid all the defs.

**Comment by jhuggins** [comment]
What do you mean by "all the usual stuff"?

**Comment by trevorcampbell** [comment]
not totally clear yet, but for example, common character font sets:
- caligraphic
- blackboard
- frak
- bold

with accents hat, tilde, bar
