### ISSUE TITLE
\dee -> \d

### ISSUE THREAD

**Issue by trevorcampbell** [trevorcampbell/shortex#42]
from another style file I saw

**Comment by jhuggins** [comment]
I like it

**Comment by trevorcampbell** [comment]
for the record: I also added the `\pd` command for `\partial`. There are other potential ideas (like `\die` and `\dabba` and other things people say in words) but I didn't see anything consistently/widely used enough to justify. Seems the best option is to keep "partial" shortened to "p" and otherwise follow the new `\d` syntax, hence `\pd`.
