### ISSUE TITLE
v/var greeks in lowercaseGreeks?

### ISSUE THREAD

**Issue by trevorcampbell** [trevorcampbell/shortex#43]
I see we have a few shortened greek letters and variants (eps, ups, veps, vtheta, etc)

need to think about whether to remove these, include them in lowercaseGreeks, or leave them in but not include them

**Comment by jhuggins** [comment]
I really like having these – super helpful. I'm less sure about including them in lowercaseGreeks. Could we make it an option...? we still have to choose a default though...

**Comment by trevorcampbell** [comment]
@jhuggins I think I found the right solution.

- for variants, just prepend `v`
- for all greeks:
    - if the name is <= 3 characters, leave it alone
    - if the name is > 3 characters, shorten it to 3. The rule is as follows:
        - for "...on" names like epsilon, upsilon, shorten to the first 3 characters (eps, ups)
        - for "...a" names like alpha, beta, gamma, shorten to the first character, a middle one, and the last. so we'd get bta, dta, ita, and so on

**Comment by jhuggins** [comment]
I think > 4 characters we shorten. It's not worth the confusion of shortening 4 characters to 3. Also, I would prefer a consistent rule of using the first three. So, all the shorthands would be:
- gamma -> gam
- kappa -> kap
- lambda -> lam
- sigma -> sig
- omicron -> omi
- omega -> ome
- epsilon -> eps
- upsilon -> ups

However, I'm not happy with omicron and omega because the trailing vowel is awkward...

**Comment by jhuggins** [comment]
Oh, there's also theta. Which doesn't seem to need shortening either, nor have a good shortened form

**Comment by trevorcampbell** [comment]
> However, I'm not happy with omicron and omega because the trailing vowel is awkward...

No need for omicron. The symbols are equivalent to roman: o and O.

> Oh, there's also theta. Which doesn't seem to need shortening either, nor have a good shortened form

This is why I went with the style I went with. My original attempt was first three chars, but theta breaks it. I want consistency here, so having one slightly weird one is no good for me.

Shortening some from >4 to 3 is also tricky, especially if we keep theta as is. Your proposal would end up with some with 2 chars, some with 3 that used to be > 4, some 3 that were 3, some 4, and one length 5 with no clear pattern.

My proposal of course isn't perfect, but I'm not sure we can reach perfection here. But at least it's very consistent: all length 2 and 3 remain the same, anything > 3 gets shortened in a consistent way.

**Comment by jhuggins** [comment]
The rule for my proposal is actually pretty simple: shorten everything more than 4 characters to the first 3 characters, unless the third character is a vowel, in which case don't shorten it. 

I agree we want consistency, but we also want readability. IMO, "dta" is not a good shorthand for "delta" and similarly for "bta".

**Comment by trevorcampbell** [comment]
Ah, I'm really not a fan of that proposal. I don't think it's reasonable to ask users to think about whether a character has a vowel in the third position before figuring out how to typeset it. That being said I understand the original shortenings aren't the best.

But I think I've found a better proposal than all of the above: shorten always to the first two characters. As it turns out, miraculously, it works. The only collision is with `\th` (the thorn character), which is easy and non-problematic to redefine in math mode only. @jhuggins thoughts?

**Comment by jhuggins** [comment]
I find many of the two-letter shortenings unintuitive/non-obvious (\de, \be, \la, ...). We need to be careful about losing too much readability in service of concision. For example, I just don't think there are significant benefits to shortening 3 or 4-letter commands. The ones that are most annoying to type are those with > 5 letters:

- \epsilon
- \lambda
- \upsilon

A couple of the 5-characters one are a little annoying:

- \alpha
- \omega

But the rest really aren't bad at all. 

One more flexible proposal would be to give an option for how much you want to shorten the greek letters:

1. none
2. a little (epsilon, lambda, and upsilon to first three letters)
3. more (my "shorten everything more than 4 letters to the first 3 letters" proposal)
4. most (your 2-letter proposal)

So, maybe we can have our cake and eat it too? We just have to decide with is the default (I would suggest option 2)

**Comment by trevorcampbell** [comment]
Hmmm... I'm still quite happy with the 2-char macros. I personally don't think they sacrifice readability.

I think this might be a symptom of a larger problem within ShorTeX (sort of discussed in #2 and #5): the tension between syntactic / WYSIWYG style macros, and semantic macros. Right now we sort of have a mish-mash of the two.

For example, one could imagine using `\R` as the definition of `\mathbb{R}` for reals, while right now we have `\reals`. Here we've gone with a semantic macro. Same with `\comps`, and things like `\given`, `\half`, and `\Lpinner`.

But elsewhere we use syntactic/wysiwyg macros. For example, `\sgn` and `\tr`, which look more like how they end up being typeset.

To make matters more complicated, some cases are actually both: e.g. `\cone` and `\conv`.

We also sometimes have two ways to do something. So like `\Lpinner` and `\lt< ..., ...\rt>`. I strongly prefer the latter syntactic shortening and find it far easier to read (essentially because it's "close" to what it would look like in the rendered document), but I imagine others prefer the semantic one.

I think I need to do a bit of thinking about this. I'm not against having a package option that swaps between the two styles of macro. And certainly for non-printing macros (like environments), I think our current set of macros strikes a good balance, so those are probably OK. It's the printing ones that are a bit troublesome.

**Comment by jhuggins** [comment]
Yes, I think #5 is getting to the heart of the issue, which is that we need to establish more concrete guidelines, although of course there will always be tricky cases (which this one clearly appears to be!). So, that's something we should prioritize doing. 

And, while I agree regarding the syntactic vs. semantic macro tension, I don't think this is the issue here. It's really a question of the "best" trade-off between brevity and readability. Personally I think  

`\beta \dist distBeta(\del, \lam)`

is much more readable than 

`\be \dist \distBeta(\de, \la)`

and so is worth the extra 4 keystrokes (all of which are "easy" / non-awkward). I'm even pretty happy writing

`\beta \dist distBeta(\delta, \lam)`

Though to go in the other direction, I actually think the one-letter abbreviations would be really nice and more intuitive plus less writing! But I bet there are a lot of conflicts. Also note there would have to be some two-letter abbreviations (e.g., `phi` -> `ph` and `psi` -> `ps`). But these are very natural because they make the correct sound (that corresponds to the letter).

**Comment by trevorcampbell** [comment]
I would love it if single-character macros would work, but they aren't really possible (there are so many conflicts with really basic latex functionality that I wouldn't be comfortable even doing the `\ifmmode newcommand \else oldcommand \fi`)

I'll think about it a bit more generally in the context of our other macros / a contributing guide before getting back to this specific issue

**Comment by trevorcampbell** [comment]
For the record: the final decision here was to abandon a full set of greek shorthands. After talking to a few users, it seems there isn't a major need for it anyway. We'll keep the shortenings of the longest letters (epsilon, upsilon, lambda) as well as variant shorthands with `\v...` instead of `\var...`
