### ISSUE TITLE
inconsistency in environment defs

### ISSUE THREAD

**Issue by trevorcampbell** [trevorcampbell/shortex#44]
some are `\long\def`, some `\newcommand`. Need to investigate a bit and decide on a consistent style for these (though may need inconsitency in some cases. My LaTeX-fu isn't good enough at the moment to know)

**Comment by jhuggins** [comment]
I believe `\def` is necessary when we want custom delimiters or specialized argument parsing, which seems to be most of the cases where we currently use it. However:
1. there are some `\def` instances that should be `\long\def` 
2. I'm unsure if `\def` is necessary for "Words with special characters"

**Comment by trevorcampbell** [comment]
Looked into it a bit. `\long\def` is for when the argument allows `\par` tokens, while `\def` does not allow it. `\newcommand` is like `\long\def`, while `\newcommand*` is like `\def`.

I think I can make these all consistent (maybe with a few minor exceptions, e.g., for `\[ ... \]`.
