### ISSUE TITLE
scurl not in the documentation

### ISSUE THREAD

**Issue by trevorcampbell** [trevorcampbell/shortex#45]
scurl is defined but missing from docs

**Comment by trevorcampbell** [comment]
In fact, I think I might change this anyway. Perhaps just redefine `\url` to detect whether it's in a footnote and adjust font size. I'll also add a package option to disable that behaviour in case it causes problems in a particular document.

Or maybe just remove scurl entirely because it's rarely used?

**Comment by jhuggins** [comment]
I didn't even know this was in here! It does seem potentially quite useful but I'm not sure it makes sense to include it...

**Comment by trevorcampbell** [comment]
After more thought, I think I'll just remove it.
