### ISSUE TITLE
Establish a contributing guide

### ISSUE THREAD

**Issue by trevorcampbell** [trevorcampbell/shortex#5]
We should establish some principles for defining new commands / shortcuts. E.g. a list of priorities when creating new commands:

- brevity
- consistency
- readability
- others?

Something I feel pretty strongly about: this style file is for "power-users," so I personally prefer brevity and consistency over plain-english readability (but usually brevity engenders readability so these aren't mutually exclusive goals). The other reason I put brevity at the top is for health reasons -- the less I type (especially special characters which require ctrl / shift / etc), the less likely I am to cause a repetitive stress injury to hands/wrists/etc.

E.g. if I could choose between `\exreals` vs `\extendedReals` vs `\er` I would have a strong preference for `\exreals`, which I think has the best tradeoff between readability and brevity of the three.

But if, say, `\exnats` was not possible to use (because of a previous basic unmutable latex define) while `\extnats` was, then I'd prefer `\extreals` for consistency's sake.

This is all open to discussion obviously, but I figured I'd try to give a sense for my style preferences.

Another (somewhat related) idea is to make sure every definition in the style file has a "long-form" that is readable, and then shortcut versions. Not sure whether this is a good idea or will just create a bunch of work to make things consistent.

Finally -- is it possible to define commands with macros? I.e. define the "bold prefix" operator, and then apply it to all characters. So if we ever want to change that prefix operator we just change one line in the style file instead of having to do it for all characters. This might also let us keep one "list of characters for which modifiers apply".

**Comment by jnegrea** [comment]
> Finally -- is it possible to define commands with macros? I.e. define the "bold prefix" operator, and then apply it to all characters. So if we ever want to change that prefix operator we just change one line in the style file instead of having to do it for all characters. This might also let us keep one "list of characters for which modifiers apply".

https://tex.stackexchange.com/a/564222

**Comment by jhuggins** [comment]
| https://tex.stackexchange.com/a/564222

@jnegrea that looks like a great solution!

**Comment by jnegrea** [comment]
I was playing with it and it is not easy to extend to greek letters, so i found a different solution im working with now...
https://stackoverflow.com/a/2958024

**Comment by trevorcampbell** [comment]
@jnegrea that is precisely what we need. Great find. Let us know how the exploration goes!

**Comment by jnegrea** [comment]
#7

**Comment by jhuggins** [comment]
@trevorcampbell want to take a pass at writing a "contributing" section to add to `example.tex` (and maybe rename to `shortex.tex`?)

**Comment by trevorcampbell** [comment]
@jhuggins sounds good. I'll add that to my queue.

**Comment by trevorcampbell** [comment]
I'm going to wait until #9 is merged to avoid conflicts

**Comment by jhuggins** [comment]
#9 is merged!
