### ISSUE TITLE
Add shorthands for abbreviations with lots of punctuation

### ISSUE THREAD

**Issue by jhuggins** [trevorcampbell/shortex#50]
Concretely: 
```
\newcommand{\eg}{e.g.,\ }
\newcommand{\etal}{et al.\xspace}
\newcommand{\ie}{i.e.,\ }
\newcommand{\aka}{a.k.a.\ }
```

**Comment by trevorcampbell** [comment]
@jhuggins before we include, can you investigate why there is a `\ ` after some of these, and `\xspace` after others? I'm not sure what the difference is / why one would want either one

**Comment by jhuggins** [comment]
`\xspace` essentially only adds a space if the next symbol is a letter, so you get  `et al.)` rather than `et al. )`. It's not perfect, however: https://tex.stackexchange.com/questions/86565/drawbacks-of-xspace

But for ie, eg, and aka, we know there should always be space, so it's safe to use `\ `. 

Note, btw, that we also use `\xspace` for names with special characters and some existing shortcuts (e.g., `\iid`, `\as`, and `\aev`).
